import { BsQrCodeScan, BsCreditCard } from "react-icons/bs";
import { MdOutlineAtm } from "react-icons/md";
import { CiBank } from "react-icons/ci";
import { PiHandCoinsDuotone } from "react-icons/pi";

export const ItemsSold = [
  "Căn hộ chung cư",
  "Nhà mặt phố",
  "Nhà riêng",
  "Nhà phố thương mại",
  "Biệt thự",
  "Đất nền",
  "Đất đai",
  "Khu nghỉ dưỡng",
  "Kho",
  "Nhà xưởng",
  "Khác"
]

export const ItemRent = [
  "Căn hộ chung cư",
  "Nhà mặt phố",
  "Nhà riêng",
  "Nhà phố thương mại",
  "Biệt thự",
  "Đất nền",
  "Đất đai",
  "Khu nghỉ dưỡng",
  "Kho",
  "Nhà xưởng",
  "Khác"
]
export const provinces = [
  { id: 1, name: "An Giang" },
  { id: 2, name: "Bà Rịa - Vũng Tàu" },
  { id: 3, name: "Bạc Liêu" },
  { id: 4, name: "Bắc Giang" },
  { id: 5, name: "Bắc Kạn" },
  { id: 6, name: "Bắc Ninh" },
  { id: 7, name: "Bến Tre" },
  { id: 8, name: "Bình Dương" },
  { id: 9, name: "Bình Định" },
  { id: 10, name: "Bình Phước" },
  { id: 11, name: "Bình Thuận" },
  { id: 12, name: "Cà Mau" },
  { id: 13, name: "Cao Bằng" },
  { id: 14, name: "Cần Thơ" },
  { id: 15, name: "Đà Nẵng" },
  { id: 16, name: "Đắk Lắk" },
  { id: 17, name: "Đắk Nông" },
  { id: 18, name: "Điện Biên" },
  { id: 19, name: "Đồng Nai" },
  { id: 20, name: "Đồng Tháp" },
  { id: 21, name: "Gia Lai" },
  { id: 22, name: "Hà Giang" },
  { id: 23, name: "Hà Nam" },
  { id: 24, name: "Hà Nội" },
  { id: 25, name: "Hà Tĩnh" },
  { id: 26, name: "Hải Dương" },
  { id: 27, name: "Hải Phòng" },
  { id: 28, name: "Hậu Giang" },
  { id: 29, name: "Hòa Bình" },
  { id: 30, name: "Hưng Yên" },
  { id: 31, name: "Khánh Hòa" },
  { id: 32, name: "Kiên Giang" },
  { id: 33, name: "Kon Tum" },
  { id: 34, name: "Lai Châu" },
  { id: 35, name: "Lạng Sơn" },
  { id: 36, name: "Lào Cai" },
  { id: 37, name: "Lâm Đồng" },
  { id: 38, name: "Long An" },
  { id: 39, name: "Nam Định" },
  { id: 40, name: "Nghệ An" },
  { id: 41, name: "Ninh Bình" },
  { id: 42, name: "Ninh Thuận" },
  { id: 43, name: "Phú Thọ" },
  { id: 44, name: "Phú Yên" },
  { id: 45, name: "Quảng Bình" },
  { id: 46, name: "Quảng Nam" },
  { id: 47, name: "Quảng Ngãi" },
  { id: 48, name: "Quảng Ninh" },
  { id: 49, name: "Quảng Trị" },
  { id: 50, name: "Sóc Trăng" },
  { id: 51, name: "Sơn La" },
  { id: 52, name: "Tây Ninh" },
  { id: 53, name: "Thái Bình" },
  { id: 54, name: "Thái Nguyên" },
  { id: 55, name: "Thanh Hóa" },
  { id: 56, name: "Thừa Thiên Huế" },
  { id: 57, name: "Tiền Giang" },
  { id: 58, name: "TP Hồ Chí Minh" },
  { id: 59, name: "Trà Vinh" },
  { id: 60, name: "Tuyên Quang" },
  { id: 61, name: "Vĩnh Long" },
  { id: 62, name: "Vĩnh Phúc" },
  { id: 63, name: "Yên Bái" }
];

export const payments = [
  { id: 1, name: "Thanh toán bằng mã QR (VNPAY)", icon: "<BsQrCodeScan/>" },
  { id: 2, name: "Thanh toán bằng thẻ ATM nội địa", icon: "<MdOutlineAtm/>" },
  { id: 3, name: "Thanh toán bằng thẻ quốc tế, Apple Pay, Google pay", icon: "<BsCreditCard/>" },
  { id: 4, name: "Thanh toán bằng ví MoMo", icon: "<CiBank/>" },
  { id: 5, name: "Chuyển khoản ngân hàng", icon: "<CiBank/>" },
  { id: 6, name: "Trả góp qua thẻ tín dụng (Visa, Master, JCB)", icon: "<PiHandCoinsDuotone/>" },
]
export const quickOptions = [
  { value: 500000, bonus: 0 },
  { value: 1000000, bonus: 0 },
  { value: 2000000, bonus: 254545 },
  { value: 3000000, bonus: 381818 },
  { value: 5000000, bonus: 727273 },
  { value: 10000000, bonus: 1636364 },
];
export const timer = [
  { id: 1, name: "1 phút" },
  { id: 2, name: "5 phút" },
  { id: 3, name: "10 phút" },
  { id: 4, name: "15 phút" },
  { id: 5, name: "30 phút" },
  { id: 6, name: "1 tiếng" },
  { id: 7, name: "3 tiếng" },
  { id: 8, name: "5 tiếng" },
  { id: 9, name: "9 tiếng" },
]